# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'JailbreakConcept' do

pod 'SVProgressHUD'

end

target 'JailbreakConceptTests' do

end

target 'JailbreakConceptUITests' do

end

